// Code generated by MockGen. DO NOT EDIT.
// Source: internal/event/publisher.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "product-api/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProductPublisher is a mock of ProductPublisher interface.
type MockProductPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockProductPublisherMockRecorder
}

// MockProductPublisherMockRecorder is the mock recorder for MockProductPublisher.
type MockProductPublisherMockRecorder struct {
	mock *MockProductPublisher
}

// NewMockProductPublisher creates a new mock instance.
func NewMockProductPublisher(ctrl *gomock.Controller) *MockProductPublisher {
	mock := &MockProductPublisher{ctrl: ctrl}
	mock.recorder = &MockProductPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductPublisher) EXPECT() *MockProductPublisherMockRecorder {
	return m.recorder
}

// PublishProductCreated mocks base method.
func (m *MockProductPublisher) PublishProductCreated(ctx context.Context, product model.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProductCreated", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishProductCreated indicates an expected call of PublishProductCreated.
func (mr *MockProductPublisherMockRecorder) PublishProductCreated(ctx, product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProductCreated", reflect.TypeOf((*MockProductPublisher)(nil).PublishProductCreated), ctx, product)
}
